### ISSUE TITLE
Octavi 5.0

### ISSUE THREAD

**Issue by TimsFong** [Hirozuto/gsi-patches#1]
hello.Octavi 5.0 when?

**Comment by hiratazx** [comment]
> hello.Octavi 5.0 when?

soon, my server is already back

**Comment by hiratazx** [comment]
**
![image](https://github.com/Hirozuto/gsi-patches/assets/123168129/24ef2c07-2b4e-4f95-b79e-c8b35f3494e6)
**
yeah, soon

**Comment by TimsFong** [comment]
> ** ![image](https://private-user-images.githubusercontent.com/123168129/287245299-24ef2c07-2b4e-4f95-b79e-c8b35f3494e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjkxNjEsIm5iZiI6MTcwMTQyODg2MSwicGF0aCI6Ii8xMjMxNjgxMjkvMjg3MjQ1Mjk5LTI0ZWYyYzA3LTJiNGUtNGY5NS1iNzllLWM4YjM1ZjM0OTRlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMVQxMTA3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZWZiYzRjY2MwYzQ4NWJhMGYxZjgyNWE1Yzg2NmFmNDJiYWMwNWNiMGJiZmE3NTliMGU0YTMxYWY1ZDBiNjI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PRwT0c30crVbNysJ_t_kyNldDOnY4cEjJTzr1BvA9yI) ** yeah, soon

thanks.waiting........download link？

**Comment by hiratazx** [comment]
> > ** ![image](https://private-user-images.githubusercontent.com/123168129/287245299-24ef2c07-2b4e-4f95-b79e-c8b35f3494e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjkxNjEsIm5iZiI6MTcwMTQyODg2MSwicGF0aCI6Ii8xMjMxNjgxMjkvMjg3MjQ1Mjk5LTI0ZWYyYzA3LTJiNGUtNGY5NS1iNzllLWM4YjM1ZjM0OTRlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMVQxMTA3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZWZiYzRjY2MwYzQ4NWJhMGYxZjgyNWE1Yzg2NmFmNDJiYWMwNWNiMGJiZmE3NTliMGU0YTMxYWY1ZDBiNjI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PRwT0c30crVbNysJ_t_kyNldDOnY4cEjJTzr1BvA9yI) ** yeah, soon
> 
> thanks.waiting........download link？

I'll post it on channel/group

**Comment by TimsFong** [comment]
> > > ** ![image](https://private-user-images.githubusercontent.com/123168129/287245299-24ef2c07-2b4e-4f95-b79e-c8b35f3494e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjkxNjEsIm5iZiI6MTcwMTQyODg2MSwicGF0aCI6Ii8xMjMxNjgxMjkvMjg3MjQ1Mjk5LTI0ZWYyYzA3LTJiNGUtNGY5NS1iNzllLWM4YjM1ZjM0OTRlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMVQxMTA3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZWZiYzRjY2MwYzQ4NWJhMGYxZjgyNWE1Yzg2NmFmNDJiYWMwNWNiMGJiZmE3NTliMGU0YTMxYWY1ZDBiNjI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PRwT0c30crVbNysJ_t_kyNldDOnY4cEjJTzr1BvA9yI) ** yeah, soon
> > 
> > 
> > thanks.waiting........download link？
> 
> I'll post it on channel/group

when？？？
